export const DUMMY = [
  {
    id: 1,
    firstName: "Katarina",
    lastName: "Yu",
    phoneNumber: "+63 927 123 1234",
    isFavorite: true,
    deliveryAddress: {
      houseNo: 719,
      street: "123 Manuel L. Quezon",
      city: "Mandaue",
      province: "Cebu",
      zipCode: 6014,
    },
    billingAddress: {
      houseNo: 719,
      street: "123 Manuel L. Quezon",
      city: "Mandaue",
      province: "Cebu",
      zipCode: 6014,
    },
  },
  {
    id: 2,
    firstName: "Katarina",
    lastName: "Yu",
    phoneNumber: "+63 927 123 1234",
    isFavorite: true,
    deliveryAddress: {
      houseNo: 719,
      street: "123 Manuel L. Quezon",
      city: "Mandaue",
      province: "Cebu",
      zipCode: 6014,
    },
    billingAddress: {
      houseNo: 719,
      street: "123 Manuel L. Quezon",
      city: "Mandaue",
      province: "Cebu",
      zipCode: 6014,
    },
  },
  {
    id: 3,
    firstName: "Katarina",
    lastName: "Yu",
    phoneNumber: "+63 927 123 1234",
    isFavorite: true,
    deliveryAddress: {
      houseNo: 719,
      street: "123 Manuel L. Quezon",
      city: "Mandaue",
      province: "Cebu",
      zipCode: 6014,
    },
    billingAddress: {
      houseNo: 719,
      street: "123 Manuel L. Quezon",
      city: "Mandaue",
      province: "Cebu",
      zipCode: 6014,
    },
  },
  {
    id: 4,
    firstName: "Katarina",
    lastName: "Yu",
    phoneNumber: "+63 927 123 1234",
    isFavorite: true,
    deliveryAddress: {
      houseNo: 719,
      street: "123 Manuel L. Quezon",
      city: "Mandaue",
      province: "Cebu",
      zipCode: 6014,
    },
    billingAddress: {
      houseNo: 719,
      street: "123 Manuel L. Quezon",
      city: "Mandaue",
      province: "Cebu",
      zipCode: 6014,
    },
  },
  {
    id: 5,
    firstName: "Katarina",
    lastName: "Yu",
    phoneNumber: "+63 927 123 1234",
    isFavorite: true,
    deliveryAddress: {
      houseNo: 719,
      street: "123 Manuel L. Quezon",
      city: "Mandaue",
      province: "Cebu",
      zipCode: 6014,
    },
    billingAddress: {
      houseNo: 719,
      street: "123 Manuel L. Quezon",
      city: "Mandaue",
      province: "Cebu",
      zipCode: 6014,
    },
  },
];